name: Build llvm release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'ddln*'
    paths:
      - '.github/workflows/release.yml'
      - 'build.sh'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Install Ninja
        uses: llvm/actions/install-ninja@main
      - uses: actions/checkout@v1
        with:
          fetch-depth: 250
      - name: Build and package
        run: ./build.sh && tar -C DIST -czf llvm.tar.gz llvm
      - uses: actions/upload-artifact@v3
        with:
          name: llvm-release
          path: llvm.tar.gz
      - name: Create release in github
        if: github.event_name == 'push'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: llvm.tar.gz
